### ISSUE TITLE
starting the container requires an internet connection

### ISSUE THREAD

**Issue by orodbhen** [docker-library/redmine#74] opened 2017-06-07 20:38 UTC
This image will not work on an air-gap network without modification.

There's a line in `docker-entrypoint.sh` that tries to connect to the internet:

    bundle install --without development test 

If I rebuild the image and comment out this line, then it works. The command is used twice in the `Dockerfile`, so I wonder if it's really necessary. I'm not a Ruby person, so I don't understand it all that well. Perhaps an env variable could be provided to disable it.

**Comment by NetworkEng** [comment] 2017-07-12 20:06
This is preventing us to deploy in production as it has no Internet access.  There has to be a better way that doesn't require Internet access when the container launches.  I also am not a ruby person, so I'm unsure why all of the potential gems were not simply added and left in the Dockerfile build.  Respectfully, please consider helping to resolve this issue.

**Comment by tianon** [comment] 2017-07-12 22:09
All the gems are added in the Dockerfile -- the reason we have to run that
command again in the entrypoint is that which gems it actually configures
for load is determined by the user-supplied configuration.  If we don't run
it again, it won't load any of the (already installed) database adapters
and the image will be arguably somewhat useless.

If there's a better way to convince it to either make that determination at
runtime or some other solution, we'd love to implement it.

**Comment by NetworkEng** [comment] 2017-07-12 23:25
Thanks @tianon .  Yes, I do not know Ruby, but I do know a fair bit of shell scripting.

This can be accomplished with 2 lines (though, multiple files in this repo would need to be updated).  Basically, just save and use adapter specific copies of the Gemfile.lock file.

First, in the Dockerfile, in the RUN section where you have a for loop to install all of the adapter files, insert this line to copy the Gemfile.lock to a file specific to that adapter.  After the line with `bundle install --without development test; \`, insert:

    cp Gemfile.lock Gemfile.lock.${adapter}; \

Then, in the `docker-entrypoint.sh` script, simply change the line that has `bundle install --without development test` to:

    cp /usr/src/redmine/Gemfile.lock.${adapter} /usr/src/redmine/Gemfile.lock

The `${adapter}` variable is already being determined and set by that point in the `docker-entrypoint.sh` script.

Viola!

**Comment by NetworkEng** [comment] 2017-07-13 00:27
Pull request #80 created.

**Comment by NetworkEng** [comment] 2017-07-13 02:17
Travis CI job failed, but pretty sure it has nothing to do with the pull request.
https://travis-ci.org/docker-library/redmine/builds/253025762?utm_source=github_status&utm_medium=notification

Could someone who is responsible for this repo please have a look?

**Comment by NetworkEng** [comment] 2017-07-13 03:35
Well, looks like I need to add a check to the entrypoint script before attempting to copy.  This is because the `${adapter}` variable is not set if the `./config/database.yml` file already exists.  E.g. when a container restarts.  At that point, though, the Gemfile.lock file should already have been copied over, so we wouldn't need to do the copy again.  Only needed on initial run when the database config file is created.

**Comment by NetworkEng** [comment] 2017-07-13 03:53
Added check to `docker-entrypoint.sh` scripts and pushed to my forked repo referenced in PR #80 

Updated line is:

    [ ! -z $adapter ] && cp /usr/src/redmine/Gemfile.lock.${adapter} /usr/src/redmine/Gemfile.lock

**Comment by NetworkEng** [comment] 2017-07-13 06:09
travis-ci checks passing now since recent update

**Comment by yosifkit** [comment] 2017-07-13 21:52
Should be fixed by #80. We'll get an update PR to official-images shortly.

**Closed by yosifkit** 2017-07-13 21:52 UTC

**Comment by NetworkEng** [comment] 2017-07-13 23:20
Thanks again @yosifkit and @tianon !

**Comment by yosifkit** [comment] 2017-07-14 00:16
PR was https://github.com/docker-library/official-images/pull/3194; so it should already be available on the Docker Hub.

**Comment by yosifkit** [comment] 2017-07-14 00:17
Thanks @NetworkEng for the simple solution. :tada:

**Comment by NetworkEng** [comment] 2017-07-14 00:19
You're quite welcome @yosifkit. Confirmed that Docker Hub has the updated image.
