### ISSUE TITLE
Seems the cache in the passenger container is "corrupted"

### ISSUE THREAD

**Issue by Angelinsky7** [docker-library/redmine#95] opened 2017-11-10 09:47 UTC
Each time i start the passenger container, some languages files are missing and i need to that to get them back :

1. Go into the running container (docker exex -ti .... bash)
2. bundle exec rake tmp:cache:clear tmp:sessions:clear RAILS_ENV=production
3. echo "restart" > tmp/restart.txt
4. Refresh a redmine page in the browser (to kick the passenger restart)
4. Repeat "2" to "4" until the cache is really cleared and my missing language are back

Usually there is  only one missing language : English (but it makes redmine not translated at all)
I've tested with or without plugins, volumes, etc... it's most of the time always the same behavior (sometime randomly i've got all the languages back, it seems linked with the boot time of the container, the slower, the worst)

Is it possible that the cache in the container contains some bad data ?
Thanks for your support !

Redmine version : 3.4.3-passenger
Docker version : 17.09.0-ce

**Comment by tianon** [comment] 2017-11-14 23:28
It's definitely possible!  Any ideas for how we could verify and/or modify the image to account for that?  Even just having a simple way to verify/reproduce the issue would likely be helpful for determining whether there's anything we can do about it. :+1:

**Comment by Angelinsky7** [comment] 2017-12-01 13:13
Hi,
i've tried a lot of test but sadly it seems very random.
Sometimes i got the issue, sometime not.... very strange.... seems completely depends on the load time of the image....

**Comment by Angelinsky7** [comment] 2017-12-18 16:40
Hi,
a little news, now for no reason, without restarting the container, i've randomly got the issue...

**Comment by wglambert** [comment] 2018-09-07 19:59
Are you still encountering this issue

**Comment by Angelinsky7** [comment] 2018-09-10 08:35
sadly i don't know. i've created a cron task that check if the cache is corrupted and restart the container after cleaning the cache... so i would need to deactivate it and test.
for now i can't do it...

**Comment by tianon** [comment] 2018-09-20 22:45
Sorry, but I'm going to close this -- we can't reproduce the issue, and it doesn't seem like anyone else is having similar issues.

If someone can come up with a simple reproducer, that would be really helpful for determining whether this is something wrong with how we've packaged the image (and thus something we can look to fix) or whether this is an issue with Redmine, its dependencies, Ruby, or even Docker (and thus not really something we could fix even if we wanted to).

**Closed by tianon** 2018-09-20 22:45 UTC
Labels: Issue
