### ISSUE TITLE
[Cronjobs] Add ability to run redmine:send_reminders regulary

### ISSUE THREAD

**Issue by Commifreak** [docker-library/redmine#237] opened 2021-04-06 06:31 UTC
Hi,

the current redmine containers does not support cronjobs afaik. Would be great to set just a config value to enable those, like: https://www.redmine.org/projects/redmine/wiki/RedmineReminderEmails

Currently I use this on the host:

```sh
#!/bin/bash
docker exec -u redmine redmine_redmine_1 rake redmine:send_reminders RAILS_ENV="production"
```

Regards,

**Comment by wglambert** [comment] 2021-04-06 15:25
Duplicate of https://github.com/docker-library/redmine/issues/64

**Closed** 2021-04-07 17:48 UTC
Labels: Request
