### ISSUE TITLE
config/configuration.yml

### ISSUE THREAD

**Issue by gkohler79** [docker-library/redmine#164] opened 2019-05-28 14:28 UTC
I'm having a terrible time getting with configuration.yml to email outbound email in my redmine setup.  I'm trying to do this through a deployment, snippets of my deployment file are below.  However, it appears I have a permissions error and the pod fails to start.  The log says this: chown changing ownership of 'config/configuration.yaml' read-only file system

If I mount the file in the /tmp filesystem it mounts just fine, but obviously that isn't helpful for enabling the email configuration.  I could use some help/suggestions on how to fix this.

    spec:
      volumes:
        - name: pv-redmine
          persistentVolumeClaim:
            claimName: redmine
        - name: redmine-secrets
          secret:
            secretName: redmine
        - name: redmine-configuration
          configMap:
            name: redmine
            items:
            - key: configuration.yml
              path: configuration.yml
      containers:
        - name: redmine
          volumeMounts:
            - name: pv-redmine
              mountPath: /usr/src/redmine/files
              subPath: files
            - name: redmine-secrets
              mountPath: /run/secrets/redmine
              readOnly: true
            - name: redmine-configuration
              mountPath: /usr/src/redmine/config/configuration.yml
              subPath: configuration.yml
          image: redmine:4.0.3

Thanks in advance!

**Comment by wglambert** [comment] 2019-05-28 16:26
Duplicate of https://github.com/docker-library/redmine/issues/20

This `.yml` might work for you https://github.com/docker-library/redmine/issues/20#issuecomment-352029332

**Comment by gkohler79** [comment] 2019-05-28 16:34
The .yml file isn't my issue, it's the fact that I inject the yml file as a config map, then the image tries to chown on that file and can't because it's read-only...

**Comment by wglambert** [comment] 2019-05-28 16:49
My mistake, the entrypoint tries modifying those files/directories
https://github.com/docker-library/redmine/blob/d7f8ec81d2ca768f84e462897b87600859e8ceb7/4.0/docker-entrypoint.sh#L32-L40

If you pre-set your permissions to match then that would work, or maybe mount the file outside of the `/usr/src/redmine/` directory and do a [config set](https://redis.io/commands/config-set)?

**Comment by gkohler79** [comment] 2019-05-28 16:52
I certainly appreciate the responsiveness!

I solved this by mounting the file in /tmp and then doing a copy from /tmp to  the redmine config directory after the post is started.

Works like a champ!

**Comment by tianon** [comment] 2019-05-30 00:02
If you already know your permissions are "good" (or at least reasonable), you should be able to run the container explicitly as the `redmine` user (or any other arbitrary user, really) and skip that failing `chown` bit entirely.  Couple that with the `no-new-privileges` security flag and you've got an even more secure configuration to boot. :+1:

**Closed** 2019-07-19 19:23 UTC
