### ISSUE TITLE
how to install new redmine plugin for container redmine

### ISSUE THREAD

**Issue by 17635386421** [docker-library/redmine#291] opened 2023-06-09 08:23 UTC
I always fail

**Comment by yosifkit** [comment] 2023-06-09 17:18
Closing as "can't reproduce". There is not enough information here to replicate the failure.

**Closed by yosifkit** 2023-06-09 17:18 UTC

**Comment by 17635386421** [comment] 2023-06-12 02:55
ArgumentError: parent directory is world writable, Bundler::FileUtils#remove_entry_secure does not work; abort: "/usr/local/bundle/gems/ox-2.14.16" (parent directory mode 40777)
