### ISSUE TITLE
Can't install additional (plugin's) gems

### ISSUE THREAD

**Issue by zx1986** [docker-library/redmine#88] opened 2017-08-25 09:57 UTC
refs: https://github.com/docker-library/redmine/pull/84

https://github.com/docker-library/redmine/blob/master/3.4/docker-entrypoint.sh#L104
https://github.com/docker-library/redmine/blob/master/3.4/Dockerfile#L79

Seems Gemfile.lock.${adapter} is copy from Gemfile.lock (which is the Redmine's original Gemfile.lock), so what is the best practices I add my own / plugins gems into that?

It didn't make sense.
It didn't handle plugins/*/Gemfile files.

**Comment by zx1986** [comment] 2017-08-25 10:39
I had found that in /usr/src/redmine/Gemfile:

```
# Load plugins' Gemfiles
Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
  eval_gemfile file
end
```

But I think it had to build an owner docker image with Dockerfile like this:

```
FROM redmine:3-passenger
ADD plugins /usr/src/redmine/
```

I can't just use this official image without build my owner one, right?

**Comment by zx1986** [comment] 2017-08-25 11:51
ok, I found the problem and change my Dockerfile to this:

```
FROM redmine:3-passenger

ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/src/redmine
COPY plugins plugins/
RUN bundle install --without development test \
    && for adapter in mysql2 postgresql sqlite3; do cp Gemfile.lock "Gemfile.lock.${adapter}"; done
```

I need to run the Redmine Gemfile's `bundle install` again after add plugins.

**Comment by yosifkit** [comment] 2017-11-03 19:31
Was this fixed by https://github.com/docker-library/redmine/pull/92?

**Comment by zx1986** [comment] 2017-11-09 21:16
I will try this again.

**Comment by wglambert** [comment] 2018-05-04 00:05
Any updates on this?

**Comment by wglambert** [comment] 2018-05-17 17:05
Assuming the issue is resolved then, going to close

**Closed by wglambert** 2018-05-17 17:05 UTC
Labels: question
