### ISSUE TITLE
login does not work

### ISSUE THREAD

**Issue by hasufell** [docker-library/redmine#46] opened 2016-12-09 12:47 UTC
used images:

* redmine:latest
* [custom mysql image](https://github.com/hasufell/docker-gentoo-mysql)
* [jwilder derived front proxy](https://github.com/hasufell/docker-exherbo-nginx-proxy)

what works:

* db access
* visiting the site, clicking on project page etc

what does not work:

* logging in via `admin/admin` -> I get redirected to `https://<the-fucking-ip-from-my-desktop-pc>/my/page`

**Comment by tianon** [comment] 2016-12-10 17:02
Can you provide a bit more detail about how you're running this, and possibly some logs from the running container?  Did you do any database setup in advance (or previously) that got included in your MySQL instance?  Are you using any of Docker for Mac, Docker for Windows, or Docker Toolbox/`docker-machine`? :confused: 

I just tested a fresh instance (`Digest: sha256:99337634dbca74affed3cb516e7241aeb83d6038b88756cbaa60d174f4fb4bc9` from `docker pull redmine`), and after entering `admin`/`admin`, I get directed to `/my/password` with `Your password has expired or the administrator requires you to change it.` (which had slightly odd field names), but after going through that I was redirected to `/my/account` correctly, so I can't reproduce the failure. :disappointed:

**Comment by wglambert** [comment] 2018-05-03 18:30
Closing since it's been a year without further comment and the issue doesn't seem to be an error with the image.

**Closed by wglambert** 2018-05-03 18:30 UTC
Labels: question
